groups:
    main: main
recognizers:
    -   name: whitespace
        outputRegex: "\\s+"
        description: Natural numbers
        active: false
    -   name: number
        outputRegex: '[0-9]+'
        description: Natural numbers
    -   name: real
        outputRegex: "([0-9]*\\.[0-9]+)"
        description: Natural numbers
    -   name: day
        outputRegex: '(0?[1-9]|[12][0-9]|3[01])'
        searchRegex: "(^|\\D)(?<main>%s)($|\\D)"
    -   name: month
        outputRegex: '(0?[1-9]|[1][0-2])'
        searchRegex: "(^|\\D)(?<main>%s)($|\\D)"
    -   name: date
        outputRegex: '[0-9]{4}-[0-9]{2}-[0-9]{2}'
        description: a date
    -   name: time
        outputRegex: "[0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]{1,3})?"
        description: The time
    -   name: ISO8601
        outputRegex: "[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]{1,3})?"
#    -   name: ISO8601 with timezone
#        outputRegex: "[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]{1,3})?[+-][0-9]{1,2}"
    -   name: String 1
        outputRegex: "'([^']|\\\\')*'"
    -   name: Hashtag
        outputRegex: "\\B#([a-z0-9]{2,})(?![~!@#$%^&*()=+_`\\-\\|\\/'\\[\\]\\{\\}]|[?.,]*\\w)"
    -   name: Email address
        outputRegex: "[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?"
#    -   name: empty
#        outputRegex: XXX
#        searchRegex: '.(?<main>).'
    -   name: loglevel
        outputRegex: '((?i)TRACE|DEBUG|INFO|NOTICE|WARN|ERROR|SEVERE|FATAL)'
        description: Level a logger may use
